// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: testTask.proto

#include "testTask.pb.h"
#include "testTask.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace handler {

static const char* MassiveHandlerService_method_names[] = {
  "/handler.MassiveHandlerService/Handle",
};

std::unique_ptr< MassiveHandlerService::Stub> MassiveHandlerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MassiveHandlerService::Stub> stub(new MassiveHandlerService::Stub(channel));
  return stub;
}

MassiveHandlerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Handle_(MassiveHandlerService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MassiveHandlerService::Stub::Handle(::grpc::ClientContext* context, const ::handler::NumberMassive& request, ::handler::Number* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Handle_, context, request, response);
}

void MassiveHandlerService::Stub::experimental_async::Handle(::grpc::ClientContext* context, const ::handler::NumberMassive* request, ::handler::Number* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, std::move(f));
}

void MassiveHandlerService::Stub::experimental_async::Handle(::grpc::ClientContext* context, const ::handler::NumberMassive* request, ::handler::Number* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::handler::Number>* MassiveHandlerService::Stub::PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::handler::NumberMassive& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::handler::Number>::Create(channel_.get(), cq, rpcmethod_Handle_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::handler::Number>* MassiveHandlerService::Stub::AsyncHandleRaw(::grpc::ClientContext* context, const ::handler::NumberMassive& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRaw(context, request, cq);
  result->StartCall();
  return result;
}

MassiveHandlerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MassiveHandlerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MassiveHandlerService::Service, ::handler::NumberMassive, ::handler::Number>(
          [](MassiveHandlerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::handler::NumberMassive* req,
             ::handler::Number* resp) {
               return service->Handle(ctx, req, resp);
             }, this)));
}

MassiveHandlerService::Service::~Service() {
}

::grpc::Status MassiveHandlerService::Service::Handle(::grpc::ServerContext* context, const ::handler::NumberMassive* request, ::handler::Number* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace handler

